name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    needs: [lint, e2e, CallKath]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Run build
        run: npm run build

      - name: Run lint
        run: npm run lint

      - name: Run prettier
        run: npm run prettier

      - name: Run E2E tests
        run: npm run test:ci

      - name: Set name
        run: echo "Kathlynne Joy Moraga - Build Completed"

      # - name: Upload Artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: coverage
