name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Create ZIP file
        run: zip -r artifacts.zip ./dist

      - name: Upload ZIP Artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-zip
          path: artifacts.zip

  lint:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run prettier
        run: npm run prettier

  unit-test:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run unit test
        run: npm run test:ci

  e2e:
    runs-on: ubuntu-latest
    needs: [unit-test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run E2E tests
        run: npm run e2e

  CallKath:
    runs-on: ubuntu-latest
    needs: [e2e]

    steps:
      - name: Set name
        run: echo "Kathlynne Joy Moraga - Test Completed"
